# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e73daa7d22fe00a58c83b94e758438c9e9c024f86fd7902b5341c9e33aa0b287f2f12672aad320642a27f9c777588d7e0c8a485ec9e98ee091e53425c681a0

test:
  secret_key_base: 1e1b4d7f4fb171951ce30382ea88cf72d91176f0ee8cf8f48c3ef3477c7d080a2cfdaf748b5e70d9ad1caa9d9b62de1b9db0b65ff85f30f2d7fa70a872c72d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
